name: healthcare-ai
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  
  # Core scientific computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  
  # Machine learning frameworks
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - tensorflow>=2.6.0
  
  # Data visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.3.0
  - bokeh>=2.4.0
  
  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=3.2.0
  - ipywidgets>=7.6.0
  - notebook>=6.4.0
  
  # Development tools
  - pytest>=6.2.0
  - black>=21.9.0
  - flake8>=3.9.0
  
  # Additional dependencies via pip
  - pip:
    - transformers>=4.12.0
    - datasets>=1.15.0
    - pydicom>=2.2.0
    - nibabel>=3.2.0
    - SimpleITK>=2.1.0
    - biopython>=1.79
    - flask>=2.0.0
    - fastapi>=0.70.0
    - uvicorn>=0.15.0
    - requests>=2.26.0
    - sqlalchemy>=1.4.0
    - pymongo>=3.12.0
    - redis>=3.5.0
    - h5py>=3.4.0
    - spacy>=3.4.0
    - nltk>=3.6.0
    - gensim>=4.1.0
    - textblob>=0.17.0
    - opencv-python>=4.5.0
    - pillow>=8.3.0
    - imageio>=2.9.0
    - statsmodels>=0.12.0
    - lifelines>=0.26.0
    - pymc3>=3.11.0
    - arviz>=0.11.0
    - fairlearn>=0.7.0
    - aif360>=0.4.0
    - shap>=0.40.0
    - lime>=0.2.0
    - eli5>=0.11.0
    - cryptography>=3.4.0
    - pycryptodome>=3.12.0
    - pytest-cov>=2.12.0
    - bandit>=1.7.0
    - safety>=1.10.0
    - sphinx>=4.2.0
    - sphinx-rtd-theme>=1.0.0
    - tqdm>=4.62.0
    - python-dotenv>=0.19.0
    - pyyaml>=5.4.0
    - click>=8.0.0
    - rich>=10.12.0
    - fhir.resources>=6.2.0
    - hl7apy>=1.3.0
    - pyxnat>=1.4.0
    - flower>=1.0.0
    - onnx>=1.10.0
    - onnxruntime>=1.9.0
    - qiskit>=0.34.0
    - codecarbon>=1.2.0
